### ISSUE TITLE
Why is my radar Drawing is empty

### ISSUE THREAD

**Issue by zkuka** [Zeldruck/Albion-Online-ZQRadar#22]
![1](https://github.com/Zeldruck/Albion-Online-ZQRadar/assets/128674840/63099562-fe9b-401c-8ee8-dc234221e244)

**Comment by Zeldruck** [comment]
Hello, this could be due to several problems. Can you take a screenshot of your terminal?

**Comment by zkuka** [comment]
> 您好，这可能是由于几个问题造成的。你能截取你的终端吗？

![1715710224734](https://github.com/Zeldruck/Albion-Online-ZQRadar/assets/128674840/147cdd25-4ffd-402a-8f51-c6f2b1ae4661)
Is this one？

**Comment by zkuka** [comment]
I tried all three ips

**Comment by Zeldruck** [comment]
I'll have to look at it later this month

**Comment by zkuka** [comment]
> Currently it's not working with vpns
Does that mean I can't use a vpn?

**Comment by zkuka** [comment]
> I'll have to look at it later this month

Thank you very much for your reply

**Comment by Zeldruck** [comment]
> > Does that mean I can't use a vpn?

In the current state of the radar yes, you cannot

**Comment by zkuka** [comment]
> > Does that mean I can't use a vpn?
> 
> In the current state of the radar yes, you cannot

But that's also the case when I don't use a vpn to access the game

**Comment by Zeldruck** [comment]
Can you show your terminal when you don't use a vpn?

**Comment by zkuka** [comment]
> Can you show your terminal when you don't use a vpn?

The same picture I posted above still has radmin vpn but I don't have a vpn.

**Comment by zkuka** [comment]
> Can you show your terminal when you don't use a vpn?

The same picture I posted above still has radmin vpn but I don't have a vpn.I need to turn on the accelerator to play this game in China, but I just played without the accelerator on the radmin vpn display

**Comment by zkuka** [comment]
> Can you show your terminal when you don't use a vpn?
The same picture I posted above still has radmin vpn but I don't have a vpn.I need to turn on the accelerator to play this game in my country, but I just played without the accelerator on the radmin vpn display

**Comment by zkuka** [comment]
> Can you show your terminal when you don't use a vpn?

The same picture I posted above still has radmin vpn but I don't have a vpn.I need to turn on the accelerator to play this game in my country, but I just played without the accelerator on the radmin vpn display

**Comment by Zeldruck** [comment]
I understand, but accelerators are vpns so it will continue not to work

**Comment by zkuka** [comment]
> I understand, but accelerators are vpns so it will continue not to work

But the problem is that I'm not using an accelerator, and there's a radmin vpn on this page. Why

**Comment by Zeldruck** [comment]
I don't know about that.
But if you are not using anything, try the number 2
And upgrade your npcap version to 1.79

**Comment by zkuka** [comment]
> I understand, but accelerators are vpns so it will continue not to work

It is already 3 am at my time, thank you very much for your reply and help, I have to go to bed. Have a good day.

**Comment by zkuka** [comment]
> I don't know about that. But if you are not using anything, try the number 2 And upgrade your npcap version to 1.79

My npcap is latest version, and I already try the number 2. thx for ur help.

**Comment by zkuka** [comment]
Брат, проблема с радаром решена, миллион раз спасибо, но мне нужно больше информации о Том, как его настроить, и зачем нужен аккаунт в программе андроида.

**Comment by zkuka** [comment]
Брат, радар показывает, что проблема решена, и большое спасибо за помощь. Но как мне сделать так, чтобы на радаре было больше радаров, и почему приложение андре залогинялось на его аккаунте.

**Comment by Zeldruck** [comment]
You can't increase the size of the radar.
As for versions, the best thing to do is join the discord, everything is updated there

**Comment by zkuka** [comment]
> You can't increase the size of the radar. As for versions, the best thing to do is join the discord, everything is updated there

I've already joined discord, so why do I need an account for Android

**Comment by Zeldruck** [comment]
You do not need an account, I think you downloaded the Qradar app and not mine, on discord in the Android channel you can find the versions

**Comment by zkuka** [comment]
> You do not need an account, I think you downloaded the Qradar app and not mine, on discord in the Android channel you can find the versions

Я получил версию андроида от discord. Спасибо за помощь, ты такой хороший человек.
