### ISSUE TITLE
SBI fixed the radar hack

### ISSUE THREAD

**Issue by tjeremypaul** [Zeldruck/Albion-Online-ZQRadar#27]
Foundation patch 3, radar doesn't work anymore

**Comment by RainyZombie** [comment]
our goated Zeldruck confirmed he's already working on this he'll probably update later

**Comment by RainyZombie** [comment]
> Foundation patch 3, radar doesn't work anymore


our goated Zeldruck confirmed he's already working on this he'll probably update later

**Comment by Iamdungx** [comment]
me either, it doesn't work anymore

**Comment by Raphael0010** [comment]
Same

**Comment by hasmal95** [comment]
Same here...

**Comment by Toxic1594** [comment]
same , discord invite seems to be broken too

**Comment by tautau-code** [comment]
same
